sonar.projectKey=javintrivedi_campus-compass-main
sonar.organization=javintrivedi

sonar.projectName=campus-compass-main
sonar.projectVersion=1.0

# Base directory for analysis
sonar.sources=.

# Exclude all non-production files from analysis entirely
sonar.exclusions=**/node_modules/**, aws_infra/**, **/*.log, backend/test/**

# Test files must be defined if we want Sonar to know they are tests
sonar.tests=backend/test

# What files should NOT count against our test coverage %
# We exclude the frontend (public) because our Mocha tests only test the backend server
sonar.coverage.exclusions=backend/public/**

sonar.qualitygate.wait=false
sonar.sourceEncoding=UTF-8

# Coverage report path
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
