apiVersion: apps/v1
kind: Deployment
metadata:
  name: campus-compass
  labels:
    app: campus-compass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campus-compass
  template:
    metadata:
      labels:
        app: campus-compass
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9000"
    spec:
      containers:
      - name: campus-compass
        image: campus-compass:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: data-storage
          mountPath: /app/backend/data
      volumes:
      - name: data-storage
        hostPath:
          path: /Users/admin52/Downloads/campus-compass-main-main/backend/data
          type: DirectoryOrCreate
