apiVersion: v1
kind: Service
metadata:
  name: campus-compass-service
  labels:
    app: campus-compass
spec:
  type: LoadBalancer
  selector:
    app: campus-compass
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30009
